### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by maaaaz** [ShawnDEvans/smbmap#12]
Hello Shawn,

As you are working on the future multi-threaded release of the tool, could you also add an option to produce a CSV output for the the dir/file listings ? 

Cheers.

**Comment by ShawnDEvans** [comment]
Hey Thomas,

Thanks a bunch for the interest in SMBMap.  Progress on it has been slow as
I've been swamped with clients and (what seems like) non-stop pen testing
and reporting.  That said, I'll certainly consider adding some form of CSV
output as the multi-threaded version is worked on.  It's about 60% of the
way there as of now.  This week is looking a bit less busy so fingers are
crossed I can make a dent in the progress.  Take care!

-Shawn

On Sat, Jul 4, 2015 at 5:19 AM, Thomas D. <notifications@github.com> wrote:

> Hello Shawn,
>
> As you are working on the future multi-threaded release of the tool, could
> you also add an option to produce a CSV output for the the dir/file
> listings ?
>
> Cheers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShawnDEvans/smbmap/issues/12>.
>



-- 
Shawn Evans
M: 724.494.3158

**Comment by a6avind** [comment]
Any update on this thread. Does SMBMAP have any kind of output flag that we can use?

**Comment by ShawnDEvans** [comment]
I totally forgot about this request. I'll see what I can do. At present there's the greppable flag which can be used to change the output, but no straight up CSV. I'll be sure to keep you posted! Thanks for bubbling this one back onto my radar.

**Comment by maaaaz** [comment]
Hello there,
@ShawnDEvans, FYI, for CSV output and global multithreading you can rip [this code](https://github.com/maaaaz/impacket/blob/master/examples/getOSandSMBproperties.py) which is also based on `impacket`.

**Comment by a6avind** [comment]
@ShawnDEvans when u are implementing output option add one for normal text output.

**Comment by ShawnDEvans** [comment]
Added a --csv option. Closing this until an issue is found with the new feature.

**Comment by noire-x** [comment]
Hi there Shawn,
im a facing an issue when using the --csv argument :
smbmap  --host-file hostslist -r --csv shares.csv
or 
smbmap  --host-file hostslist -r --csv shares
or 
smbmap -r --csv test.csv -H 192.168.0.1
or 
smbmap -r --csv test -H 192.168.0.1
results in:
smbmap: error: unrecognized arguments: --csv

What i am doing wrong? Could you help with the syntax?
Many thanks!
