### ISSUE TITLE
Problem with shebang

### ISSUE THREAD

**Issue by sbrun** [ShawnDEvans/smbmap#13]
Hello,
In the file the shebang is now #pwi! /usr/bin/env python2
When using a helper-script in kali to start the smbmap, this line is considered as a comment and the program doesn't start.
Please replace it with #! /usr/bin/env python2
Thanks

**Comment by Wh1t3Fox** [comment]
+1

**Comment by ShawnDEvans** [comment]
VIM fail ha, pushing fix now
