### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by VitaliyYakob** [ShawnDEvans/smbmap#20]
Hello Shawn.

I'm using smbmap.py on MacOS, it works. But I discovered the problem.
smbmap.py --host-file ./HOSTS.txt -u 'user' -p 'password' -d 'domain'

[+] IP: 10.10.10.1:445	Name: host1.domain.com                 
	Disk                                                  	Permissions
	----                                                  	-----------
	ADMIN$                                            	NO ACCESS
	C$                                                	        NO ACCESS
	IPC$                                              	        READ ONLY
    **Пример шары                                        READ ONLY**
[+] IP: 10.10.10.2:445	Name: host2.domain.com                 
	Disk                                                  	Permissions
	----                                                  	-----------
	ADMIN$                                            	NO ACCESS
	C$                                                	        NO ACCESS
	IPC$                                              	        READ ONLY
	print$                                            	        READ ONLY
	Test                                              	        READ ONLY
     **т ест_                                            	        READ ONLY
	Тест                                              	        READ ONLY**

I get the normal output.

smbmap.py --host-file ./HOSTS.txt -u 'user' -p 'password' -d 'domain' > ./list.txt

cat list.txt 
[+] IP: 10.10.10.1:445	Name: host1.domain.com                  
	Disk                                                  	Permissions
	----                                                  	-----------
	ADMIN$                                            	NO ACCESS
	C$                                                	        NO ACCESS
	IPC$                                              	        READ ONLY
**[!] 'ascii' codec can't encode characters in position 1-6: ordinal not in range(128)
(<type 'exceptions.UnicodeEncodeError'>, 'smbmap.py', 906)**
[+] IP: 10.10.10.2:445	Name: host2.domain.com                 
	Disk                                                  	Permissions
	----                                                  	-----------
	ADMIN$                                            	NO ACCESS
	C$                                                	        NO ACCESS
	IPC$                                              	        READ ONLY
	print$                                            	        READ ONLY
	Test                                              	        READ ONLY
**[!] 'ascii' codec can't encode character u'\u0442' in position 1: ordinal not in range(128)
(<type 'exceptions.UnicodeEncodeError'>, 'smbmap.py', 906)**

In that case, I already get the problem.

**Comment by maaaaz** [comment]
@VitaliyYakob,
You used Python 2 or Python 3 to get that result ? My guess is that you used [Python 2](https://smorbieu.gitlab.io/encoding-in-python/) :)

**Comment by ShawnDEvans** [comment]
I'm not quite sure why you're seeing that result @VitaliyYakob. In a linux environment I don't have the same issue. I'd recommend creating a VBox VM with your fav Linux distro and see if you continue to have problems. I just created a share with a unicode name and everything worked perfectly:

wtf@pop-os:~/tools/smbmap$ ./smbmap.py -H 192.168.86.29 -u 'administrator' -p 'asdf1234' 
[+] IP: 192.168.86.29:445       Name: 192.168.86.29                                     
        Disk                                                  	Permissions	Comment
	----                                                  	-----------	-------
	ADMIN$                                            	READ, WRITE	Remote Admin
	C$                                                	READ, WRITE	Default share
	IPC$                                              	NO ACCESS	Remote IPC
	Temp                                              	READ, WRITE	
	Users                                             	READ, WRITE	
	**Пример шары                                       	READ, WRITE**	
wtf@pop-os:~/tools/smbmap$ ./smbmap.py -H 192.168.86.29 -u 'administrator' -p 'asdf1234' > asdf.txt
wtf@pop-os:~/tools/smbmap$ cat asdf.txt 
[+] IP: 192.168.86.29:445       Name: 192.168.86.29                                     
        Disk                                                  	Permissions	Comment
	----                                                  	-----------	-------
	ADMIN$                                            	READ, WRITE	Remote Admin
	C$                                                	READ, WRITE	Default share
	IPC$                                              	NO ACCESS	Remote IPC
	Temp                                              	READ, WRITE	
	Users                                             	READ, WRITE	
	**Пример шары                                       	READ, WRITE**

**Comment by ShawnDEvans** [comment]
I just realized this is like 2 years old. Python3 clears this all up. Closing it.
