### ISSUE TITLE
Password is visible

### ISSUE THREAD

**Issue by amanrawat003** [ShawnDEvans/smbmap#26]
We are facing issue while reveling the password because it gets save in our history where multiple users has access to the same terminal, Can it be password protected

**Comment by a6avind** [comment]
You can add a password prompt if no password is specified. Doesn't that work @ShawnDEvans?

**Comment by ShawnDEvans** [comment]
I'll see what I can do, this should be a pretty straight forward change. Def not something you want in your history, and I think a few minor changes should make a prompt possible while retaining NULL/Guest session enumeration.

**Comment by maaaaz** [comment]
Idea : https://pymotw.com/3/getpass/

**Comment by ShawnDEvans** [comment]
I added a --promopt arg that should address your password disclosure concerns. I'm going to close this for now. If you note any problems with the new feature, please drop another issue. Thanks for the feedback!
