### ISSUE TITLE
smbmap should show comments

### ISSUE THREAD

**Issue by FireFart** [ShawnDEvans/smbmap#27]
If a share contains some comments, they are currently not shown in smbmap. `smbclient -L` shows them correctly. I think it would be nice to show comments if there are some as they can contain valuable information.

Example config:
```text
[share]
    comment = "Example Samba Server"
    path = /home/test/
    read only = yes
    browsable = yes
    public = yes
    force user = nobody
    force group = nogroup
```

**Comment by ShawnDEvans** [comment]
I'll have to look into this one to see if it's possible. The -L feature requires admin rights on the target host to execute remote commands to attain the list of mounted drives and corresponding details. I'm not entirely sure it's possible to obtain that info without remote command execution.  Solid idea all the same, so I'll look into it.

**Comment by ShawnDEvans** [comment]
Feature added. I still need to add it to the greppable output, but at least it's in the standard drive list for now.
