### ISSUE TITLE
package inclusion into distro

### ISSUE THREAD

**Issue by chadillac** [ShawnDEvans/smbmap#3]
Like the new tool! Would like to include it into ArchAssault as an official package for our users.

1.) could you include whatever license you are releasing the code under?

2.) could you offer up a tagged release?

#1 being the most important of these 2 things.

Thanks in advance!
- Chad

**Comment by ShawnDEvans** [comment]
Hey Chad,

Thanks for getting in touch with me.  I'd love to have SMBMap included in the ArchAssult distro!  I've added the appropriate license file to the repository as requested.  Regarding #2, I'm not exactly sure what a tagged release is, or how to offer one.  Please advise, I'm a bit new to this process (and git in general).  Many thanks!

-Shawn

**Comment by chadillac** [comment]
Hi Shawn,

Awesome, thank you for the licensing, at the very least we can get a package up and running with HEAD.  Tagged releases are basically snapshots of a repo at a given point in time when the authors consider it "stable for relase", take a look at metasploit as an example (https://github.com/rapid7/metasploit-framework/releases).  When you tag a release it will give other projects a static target for their packages.  This means that rather than relying on HEAD and whatever instabilities it might package managers can basically pin a version they'll build for distribution that won't be affected by new changes pushed to HEAD until the next official release is tagged.  It also makes it so the project can easily be fetched at a specific version in an archived format (zip, tar.gz), which is handy when doing PKGBUILDs.

Tagging a release is dead simple, here is a quick guide on the process.

https://help.github.com/articles/creating-releases/

Hope this helps!

I've already started working on the PKGBUILD for inclusion into ArchAssault, so it should be included within our package offerings fairly soon!

- Chad

**Comment by ShawnDEvans** [comment]
Hey Chad,

I believe I have the tagged release in order.  Please let me know if I created it correctly.  Thanks again!

-Shawn

**Comment by chadillac** [comment]
Looks good!

Thanks for that, we'll be getting this packaged up and added to the distro soon!
