### ISSUE TITLE
Command execution broken with python 3

### ISSUE THREAD

**Issue by camas** [ShawnDEvans/smbmap#37]
https://github.com/ShawnDEvans/smbmap/blob/fb4b082b3682317a692765f59fe224e821c44871/smbmap.py#L227

`data` is a `bytes` type and can't be appended to a `str` type

```
$ python smbmap.py ... -x "whoami"
[+] Finding open SMB ports....
[+] User SMB session established on redacted...
[!] Something went wrong: can only concatenate str (not "bytes") to str
```

**Comment by ShawnDEvans** [comment]
Good catch, I'm looking into it

**Comment by ShawnDEvans** [comment]
I think I squashed the bug, but it wasn't exactly an exhaustive QA process. Let me know if you run into any other issues. Thanks for reporting it!
