### ISSUE TITLE
-A pattern not working or ?

### ISSUE THREAD

**Issue by ChamDK** [ShawnDEvans/smbmap#42]
trying to download a samba share with all files.

command:

smbmap -u test -p test -H 192.168.1.100 -s C$ -R 
i get all the shares, and files listed.

if i add a -A to the end
smbmap -u test -p test -H 192.168.1.100 -s C$ -R -A '.*'

then nothing. no files are found, it lists the directorys though, but no downloads.

eighter i do not understand the command, or it is not working.

version: 1.1.0+git20191013-1

**Comment by ShawnDEvans** [comment]
i need to update the usage i think. -R accepts a path as an argument. Try this:

$ ./smbmap -u test -p test -H 192.168.1.100 -R c$ -A '.*' 

-R and -r (recursive and non recursive) listing each accept a path as an argument. If you're doing the entire C$ though, you may also want to limit the depth (--depth) and consider using -q (quiet) to prevent SMBMap from returning the entire contents of the drive.  Please let me know if this helps. Thanks!!

**Comment by squid22** [comment]
Yea, I can also confirm this is isn't working as expected either.
smbmap -u user123 -p passwd123 -d LAB -H 10.20.30.40 -R Stuff -A 'test.xml'

If remove the -A 'test.xml', I can see all the files listed recursively including the 'test.xml' which is the file i want to download automatically.
