### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by Franchium** [ShawnDEvans/smbmap#43]
I got this error on arch derivative distro, but when I'm using it on Kali/Parrot OS there's no error comes up.

![2020-02-03-043725_1366x768_scrot](https://user-images.githubusercontent.com/41231953/73956909-31c1c480-4938-11ea-9dc3-c8deb67ea875.png)

**Comment by ShawnDEvans** [comment]
Using the Impacket SMBServer library to fire up an SMB server i was able to validate it's possible to authenticate using NULL credentials: 

```
$ ./smbmap.py -H 192.168.8.45 -u '' -p ''
[+] Guest SMB session established on 192.168.86.45...
[+] IP: 192.168.8.45:445	Name: pop-os.lan                                        
	Disk                                                  	Permissions	Comment
	----                                                  	-----------	-------
	IPC$                                              	READ, WRITE	
	TYQASGEGRD                                        	READ, WRITE	P0w3r$he11
```

It's likely the host you're attempting to authenticate to does not have NULL sessions enabled.
