### ISSUE TITLE
Does smbmap support CIDR notation?

### ISSUE THREAD

**Issue by a6avind** [ShawnDEvans/smbmap#44]

**Comment by ShawnDEvans** [comment]
I just tested it, and CIDR notation appeared to be functional. CIDR notation is only compatible with the -H argument. The --host-file argument  does not yet support CIDR.

**Comment by a6avind** [comment]
sudo smbmap -H 10.11.1.1/24
[!] Invalid host...
Am I doing something wrong here?

**Comment by ShawnDEvans** [comment]
Did you close the latest greatest?

**Comment by a6avind** [comment]
Ya it works when you provide a network id not an IP address with CIDR notation.

**Comment by ShawnDEvans** [comment]
OK, i just pushed an update. I think it should address the problem with having the host bit set to a non-zero value. Let me know if it did the trick, and we can close this one out. Thanks!

**Comment by a6avind** [comment]
It's working. What is the pipeline for kali repo?

**Comment by ShawnDEvans** [comment]
I wish I knew more about how to get the latest greatest into Kali, but I'm pretty uninformed about the workflow. For now just clone the GitHub repo for the latest stable. Thanks again for the feedback!
