### ISSUE TITLE
445 not open

### ISSUE THREAD

**Issue by aaaguirrep** [ShawnDEvans/smbmap#47]
Hi, I am experimenting the next issue when I use smbmap. If I try twice o three times it works.

```bash
python3 smbmap.py -H x.x.x.x -u 'myuser' -p 'mypass'
[!] 445 not open on x.x.x.x....
```

I don't know if the issue is expected or I need to check any thing.

Regards,
Arsenio

**Comment by ShawnDEvans** [comment]
In an effort to squeeze performance I dialed back the TCP socket timeout for open port detection. I slid it back up a few milliseconds. Hopefully this helps. I'll plan on adding a parameter to set this value via the command line.

**Comment by ShawnDEvans** [comment]
I revamped the entire port detection function, and mapped it to a thread pool. It's a significantly faster, and the timeout is a full second, which should eliminate false negatives. I'm going to close this for now.  Thank you for the feedback and bug report!
