### ISSUE TITLE
Make a pypi package

### ISSUE THREAD

**Issue by maaaaz** [ShawnDEvans/smbmap#48]
@ShawnDEvans, it would help people and maintainers if you could package `smbmap` in a standard Python package that could be available on pypi.org.

Take a look at my simple packages, like [`nmaptocsv`](https://pypi.org/project/nmaptocsv), it's quite easy :)

**Comment by ShawnDEvans** [comment]
You know I tried this not too long ago, and failed hard ha. I'll try to revist once I have some more time. I had it up on PyPi, but it was installed like a library vs something you could execute. I need to do some more research, thanks for the link. This is def on my radar.

**Comment by maaaaz** [comment]
`installed like a library vs something you could execute`: I know what you mean, yes there are some traps not fall into.

If I find some time I'll prepare the package and show you how to use it ! You will just have to upload it with your account on pypi.

**Comment by jayrod** [comment]
I would like to help with this item as well. As I would like to use smbmap as a library and as a CLI tool.

**Comment by alichtman** [comment]
Hey @ShawnDEvans,

I created https://pypi.org/project/smbmap/1.8.2/. Happy to add you as a maintainer if you comment your pypi handle.

**Comment by TheProdigyLeague** [comment]
@ShawnDEvans 
#72 #78 #81 

- fixed typos
- edited minor syntactical errors
- edited some style mechanics (ascii)

**Comment by ShawnDEvans** [comment]
This is awesome, thanks for doing this! At some point a while ago I tried
to go the PyPi route and failed spectacularly at packaging it up correctly
ha. So, thanks again!

-Shawn

**Comment by maaaaz** [comment]
Thank you all

**Comment by alichtman** [comment]
@ShawnDEvans optimally, I wouldn't be responsible for creating a new pypi release every time you cut a new release on github. Github Actions supports creating a new pypi release automatically. For you to set this up, you'd need to:

1. create a PyPi account
2. be added as a maintainer of the `smbmap` package
3. configure the `python-publish.yml` action with your PyPi API key

Would you be interested in setting this up?

**Comment by ShawnDEvans** [comment]
I'm just thrilled you set it up once man! I'm down for taking a stab at
figuring it out. Thanks for the assistance. I may reach out if I got a
wall. Thanks!

**Comment by alichtman** [comment]
Another possibility would be adding me as a maintainer of smbmap, and I can set up the action.
