### ISSUE TITLE
Typo in help output

### ISSUE THREAD

**Issue by hawkinsst7** [ShawnDEvans/smbmap#51]
Small typo in -h output.

The last example uses -h <IP> instead of-H.

> $ smbmap -u 'apadmin' -p 'asdf1234!' -d ACME -h 10.1.3.30 -x 'net group "Domain Admins" /domain'

should probably be 
> $ smbmap -u 'apadmin' -p 'asdf1234!' -d ACME -H 10.1.3.30 -x 'net group "Domain Admins" /domain'

**Comment by ShawnDEvans** [comment]
Updated!
