### ISSUE TITLE
RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by relector-tuxnix** [ShawnDEvans/smbmap#85]
When listing out files and shares with the -r option its possible to hit the maximum number of file descriptors (ulimit):

![error](https://github.com/ShawnDEvans/smbmap/assets/1979197/4c9b3967-83c2-47e0-8cb9-61c44eaed862)

https://stackoverflow.com/questions/71642653/how-to-resolve-the-error-runtimeerror-received-0-items-of-ancdata

It would be nice to either have a warning when that limit is hit or to have the limit raised for the process using:

```
import resource
rlimit = resource.getrlimit(resource.RLIMIT_NOFILE)
resource.setrlimit(resource.RLIMIT_NOFILE, (4096, rlimit[1]))
```
The above addition into smbmap.py worked for me.

**Comment by ShawnDEvans** [comment]
TIL - I'll drop that code in. Thanks!

**Comment by ShawnDEvans** [comment]
Added! I have personally never experienced the same issue, so I just rolled with your propose solution. Thanks a bunch!
