### ISSUE TITLE
Export CSV not populating data

### ISSUE THREAD

**Issue by eiu-aballison** [ShawnDEvans/smbmap#87]
Using 1.9.1 when trying to export csv it creates the file, add header to the file but does not populate the data. It will display the permissions to the screen but not in the csv file. Tested with -g and it exports the information but not with --csv.

**Comment by ShawnDEvans** [comment]
I'll check it out. 100% didn't test everything well enough. Thanks for the
submission!

**Comment by ShawnDEvans** [comment]
I just pushed some code that should address the issues. Take it for a test drive! Thanks again for the bug report.
