### ISSUE TITLE
scanning for anonymous smb shares 

### ISSUE THREAD

**Issue by sec13b** [ShawnDEvans/smbmap#90]
[*] scanning for anonymous smb shares  --> /smb_dump                                                                                                                     
Traceback (most recent call last):                                                                                                                                       
  File "/usr/bin/smbmap", line 33, in <module>                                                                                                                           
    sys.exit(load_entry_point('smbmap==1.9.2', 'console_scripts', 'smbmap')())                                                                                           
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                            
  File "/usr/lib/python3/dist-packages/smbmap/smbmap.py", line 1435, in main                                                                                             
    host = [ host for host in share_drives_list.keys() ][0]                                                                                                              
                              ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                     
AttributeError: 'bool' object has no attribute 'keys'     

I get this error all time .

**Comment by ShawnDEvans** [comment]
Thanks for reporting! I'll look into it and get back to you.

**Comment by ShawnDEvans** [comment]
Cloudy you paste the command you were trying to execute at the time? I
think you're hitting an exception in the get_shares() function, which
returns False. Rather than returning False it should probably just return a
zero length dict. I'm also at a bit of a loss where the output "scanning
for anonymous smb shares" is coming from. Are you using the latest stable?
Thanks again!

**Comment by ShawnDEvans** [comment]
I pushed some changes that should address your issue. You reported this at the perfect time. I'm on an internal assessment this week and was able to reproduce your result and push a patch. I'm going to close this for now, but please let me know if your mileage varies and I'll reopen the ticket. Thanks!

**Comment by ShawnDEvans** [comment]
I fixed the exception, but SMBMap, CrackMapExec and other tools based on
Impacket have had some issues properly processing NULL authentication.
Sometimes smbclient works, other times it doesn't. It's a bit of a crap
shoot. I personally use enu4mlinux (stil) for NULL sessions (which is
either smbclient or rpclient depending on how you look at it). In any case,
reopen this issue if you run into any other problems. Thanks!
