### ISSUE TITLE
Provide a list of IP addresses does not work

### ISSUE THREAD

**Issue by xkill** [ShawnDEvans/smbmap#92]
When provide a list of IP addresses, it returns the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/smbmap", line 33, in <module>
    sys.exit(load_entry_point('smbmap==1.9.3.1', 'console_scripts', 'smbmap')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/smbmap-1.9.3.1-py3.11.egg/smbmap/smbmap.py", line 1323, in main
    elif socket.gethostbyname(host):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by ShawnDEvans** [comment]
I added more graceful host verification and error handling. It should address the issue you had with an invalid host in the list. I need to add a bit more for file handling, so I'll leave this one open.

**Comment by ShawnDEvans** [comment]
I mirrored the error checking for --host-file inputs. It should be good to go go. Thanks very much for the bug report!
