### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'keys'

### ISSUE THREAD

**Issue by allendemoura** [ShawnDEvans/smbmap#98]
![image](https://github.com/ShawnDEvans/smbmap/assets/90939597/62eaea3a-a6d4-40c1-bfc0-ef0c79d34ae2)
 consistently getting errors when trying to run scans on Offsec Proving grounds machines.

this one in particular is called 'Internal' and is running an old version of windows (Windows Server 2008 SP1 according to nmap), but the program has been hanging for me on all sorts of hosts.

in general regardless of error, the scans never seem to finish.

**Comment by JustDeadly** [comment]
tried the pip intall on Kali, still no bueno!
same results as the previous guy.. sad :(

**Comment by ShawnDEvans** [comment]
Patch pushed, should be good to go go
